---
title: "Gather information"
author: "Megan Mackey"
date: "10/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
```

```{r load-league-data, include = FALSE}
## Load CSV
## Source: http://www.football-data.co.uk/englandm.php
E0_2005 <- read.csv("Data/E0_2005.csv", stringsAsFactors = FALSE)
E0_2006 <- read.csv("Data/E0_2006.csv", stringsAsFactors = FALSE)
E0_2007 <- read.csv("Data/E0_2007.csv", stringsAsFactors = FALSE)
E0_2008 <- read.csv("Data/E0_2008.csv", stringsAsFactors = FALSE)
E0_2009 <- read.csv("Data/E0_2009.csv", stringsAsFactors = FALSE)
E0_2010 <- read.csv("Data/E0_2010.csv", stringsAsFactors = FALSE)
E0_2011 <- read.csv("Data/E0_2011.csv", stringsAsFactors = FALSE)
E0_2012 <- read.csv("Data/E0_2012.csv", stringsAsFactors = FALSE)
E0_2013 <- read.csv("Data/E0_2013.csv", stringsAsFactors = FALSE)
E0_2014 <- read.csv("Data/E0_2014.csv", stringsAsFactors = FALSE)
```

```{r choose-columns, include = FALSE}
col_chosen <- c("HomeTeam", "AwayTeam", "Date", "FTHG", "FTAG", "FTR", "HTHG", "HTAG", "HTR", "HS", "AS", "HST", "AST", "HF", "AF", "HC", "AC", "HY", "AY", "HR", "AR")

```

```{r combine-datasets-to-create-seasons, include = FALSE}
df_2005 <- data.frame(Season = "2005-2006", E0_2005[, col_chosen])
df_2006 <- data.frame(Season = "2006-2007", E0_2006[, col_chosen])
df_2007 <- data.frame(Season = "2007-2008", E0_2007[, col_chosen])
df_2008 <- data.frame(Season = "2008-2009", E0_2008[, col_chosen])
df_2009 <- data.frame(Season = "2009-2010", E0_2009[, col_chosen])
df_2010 <- data.frame(Season = "2010-2011", E0_2010[, col_chosen])
df_2011 <- data.frame(Season = "2011-2012", E0_2011[, col_chosen])
df_2012 <- data.frame(Season = "2012-2013", E0_2012[, col_chosen])
df_2013 <- data.frame(Season = "2013-2014", E0_2013[, col_chosen])
df_2014 <- data.frame(Season = "2014-2015", E0_2014[, col_chosen])
df_raw <- rbind(df_2005,df_2006, df_2007, df_2008, df_2009,
                df_2010, df_2011, df_2012, df_2013, df_2014)
df_raw$Date <- as.Date(df_raw$Date, "%d/%m/%y")

```

```{r create-functions-to-help, include = FALSE}


```

