---
title: "Gather info transfer"
author: "Megan Mackey"
date: "11/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(ggplot2)
library(rstanarm)
library(stringr)
library(rsample)
library(workflows)
library(parsnip)
library(recipes)
library(yardstick)
library(tune)
```

```{r read in data for transfer}
highest_transfer <- read_excel("transfer.xlsx") %>%
rename(team = Team,
       highest_fee = `Transfer Record (Millions of Pounds)`)

transfer_final <- inner_join(finance_final, highest_transfer, by = "team")
```

```{r create model for transfer and position}
set.seed(10)
transfer_split <- initial_split(transfer_final, prob = 0.80)
transfer_train <- training(transfer_split)
transfer_test  <- testing(transfer_split)
transfer_folds <- vfold_cv(transfer_train, v = 10)

transfer_wfl <- workflow() %>%
  add_model(linear_reg() %>% 
              set_engine("lm") %>% 
              set_mode("regression")) %>%
add_recipe(recipe(highest_fee ~ position, 
                    data = transfer_train) %>%
  step_dummy(all_nominal())) 


transfer_rs <- transfer_wfl %>%
fit_resamples(resamples = transfer_folds, 
                control = control_resamples(save_pred = TRUE)) 

predictions<- collect_predictions(transfer_rs)

predictions %>% 
  ggplot(aes(x = highest_fee , y = .pred)) + 
  geom_point(alpha = .15) +
  geom_abline(col = "red") +
coord_flip() +
labs( x = "Position", y = "Record Transfer Fee",
      title = "Relationship between position and record transfer fee",
      subtitle = " Source : https://www.transfermarkt.co.uk")

  
```


```{r save}
save(transfer_final, file = "processed_data_transfer.rda")
```

