---
title: "GIFS"
author: "Megan Mackey"
date: "11/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gganimate)
```

```{r}
season_2009_2010 <- df_all %>%
   filter(season == "2009-2010") %>%
   
   ggplot(aes(x = num_match , y = position, color = team)) +
   geom_line()+
   labs(title = "Change in position over the 2009-2010 season", 
        x = " Number of match", y = "League Position") +
    transition_reveal(date)

anim_save("2009_2010.gif", season_2009_2010)
```

```{r}
 season_2010_2011 <- df_all %>%
   filter(season == "2010-2011") %>%
   
   ggplot(aes(x = num_match , y = position, color = team)) +
   geom_line()+
   labs(title = "Change in position over the 2010-2011 season", 
        x = " Number of match", y = "League Position") +
    transition_reveal(date)

anim_save("2010_2011.gif", season_2010_2011)
```

```{r}
 season_2011_2012 <- df_all %>%
   filter(season == "2011-2012") %>%
   
   ggplot(aes(x = num_match , y = position, color = team)) +
   geom_line()+
   labs(title = "Change in position over the 2011-2012 season", 
        x = " Number of match", y = "League Position") +
    transition_reveal(date)

anim_save("2011_2012.gif", season_2011_2012)
```

```{r}
 season_2012_2013 <- df_all %>%
   filter(season == "2012-2013") %>%
   
   ggplot(aes(x = num_match , y = position, color = team)) +
   geom_line()+
   labs(title = "Change in position over the 2012-2013 season", 
        x = " Number of match", y = "League Position") +
    transition_reveal(date)

anim_save("2012_2013.gif", season_2012_2013)

```

```{r}
 season_2013_2014 <- df_all %>%
   filter(season == "2013-2014") %>%
   
   ggplot(aes(x = num_match , y = position, color = team)) +
   geom_line()+
   labs(title = "Change in position over the 2013-2014 season", 
        x = " Number of match", y = "League Position") +
    transition_reveal(date)

anim_save("2013_2014.gif", season_2013_2014)
 
```

```{r}
 season_2014_2015 <- df_all %>%
   filter(season == "2014-2015") %>%
   
   ggplot(aes(x = num_match , y = position, color = team)) +
   geom_line()+
   labs(title = "Change in position over the 2014-2015 season", 
        x = " Number of match", y = "League Position") +
    transition_reveal(date)

anim_save("2014_2015.gif", season_2014_2015)
```

```{r}
plot_2 <- case_when(
season == "2009-2019" ~ list(
                                src = './Gifs/2009_2010.gif',
                               contentType = 'image/gif',
                              width = 700,
                              height = 400),
season == "2010-2011" ~ list( src = './Gifs/2010_2011.gif',
                                    contentType = 'image/gif',
                                    width = 700,
                                    height = 400),
season == "2011-2012" ~ list(src = './Gifs/2011_2012.gif',
                                   contentType = 'image/gif',
                                   width = 700,
                                   height = 400),
season == "2012-2013" ~ list(src = './Gifs/2012_2013.gif',
                                   contentType = 'image/gif',
                                   width = 700,
                                   height = 400),
season == "2013-2014" ~ list(src = './Gifs/2013_2014.gif',
                                   contentType = 'image/gif',
                                   width = 700,
                                   height = 400),
season == "2014-2015" ~ list(src = './Gifs/2014_2015.gif',
                                   contentType = 'image/gif',
                                   width = 700,
                                   height = 400),
  TRUE ~ list(src = './Gifs/2009_2010.gif',
              contentType = 'image/gif',
              width = 700,
              height = 400) %>%
  .[[1]]
    )
```

