---
title: "Tester for model"
author: "Megan Mackey"
date: "11/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
library(gt)
library(rstanarm)
library(rsample)
library(workflows)
library(parsnip)
library(recipes)
library(yardstick)
library(GPfit)

data("processed_data_finance_edit.rda")
```

```{r}
 set.seed(10)
  
  finance_split <- initial_split(finance_final, prob = 0.80)
  
  finance_train <- training(finance_split)
  finance_test  <-  testing(finance_split)
  finance_folds <- vfold_cv(finance_final, folds = 7)
  
  finance_rec <- workflow() %>%
  add_model(linear_reg() %>% 
              set_engine("lm") %>% 
              set_mode("regression")) %>%
  add_recipe(recipe(`Total Payment` ~ position + team,
           data = finance_train) %>%
             step_dummy(all_nominal()))%>%
    fit(data = finance_test) %>%
predict(new_data = finance_test)


  
  model <- ggplot(finance_test, aes(x = position, y = `Total Payment`)) +
    geom_point(alpha = 0.2) + 
geom_smooth(method = lm, formula = y ~ x, se = FALSE) +
    scale_x_log10() + 
    scale_y_log10() + 
    labs(x = "Position in league", y = "Total Payment in millions (GBP)") +
    labs(title = " Relationship between position and total payment") +
scale_x_continuous(breaks = c(1,5,10,15,20))



```

```{r}
cor_table <- finance_final %>% 
  group_by(season) %>% 
  summarize(cor = cor(position, `Total Payment`, use = "complete.obs"), .groups = "drop") %>%
  mutate(cor = round(cor, digits = 2)) %>% 
  gt() %>%
cols_label(season = md("**Season**"),
             cor = md("**Correlation Coefficient**")) %>%
  cols_align(columns = "season", align = "left") %>% 
  tab_options(container.height = 535) %>% 
  tab_header(title = "Position and Total Payment per season",
             subtitle = "Strength of Relationship by Season")


```

```{r}
comp_model <- stan_glm(data = finance_final, 
         formula = `Total Payment` ~ position + team,
         refresh = 0)

comp_model %>%
as_tibble() %>%
mutate(manu_payment = `(Intercept)` + `teamMan United`) %>%
mutate(tottenham_payment = `(Intercept)` + teamTottenham) %>%
select(manu_payment, tottenham_payment) %>% 
  pivot_longer(cols = manu_payment:tottenham_payment, 
               names_to = "Team",
               values_to = "payment") %>% 
  ggplot(aes(payment, fill = Team)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),
                   alpha = 0.5, 
                   bins = 100, 
                   position = "identity") +
    labs(title = "Posterior Probability Distribution",
         subtitle = "Comparing Tottenham and Man United",
         x = "Average  Payment received",
         y = "Probability") + 
    scale_x_continuous(labels = scales::number_format()) +
    scale_y_continuous(labels = scales::percent_format()) +
    theme_classic() +
scale_fill_discrete(labels = c("Man United", "Tottenham"))


```

```{r}
highest_transfer %>%
rename(`Transfer Record (Millions of Pounds)` = highest_fee,
       Team = team) %>%
gt()
```

```{r}
set.seed(8)
  finance_split <- initial_split(finance_final, prob = 0.80)
  
  finance_train <- training(finance_split)
  finance_test  <-  testing(finance_split)
  finance_folds <- vfold_cv(finance_final, folds = 7)
  
  finance_rec <- workflow() %>%
    add_model(linear_reg() %>% 
                set_engine("stan") %>% 
                set_mode("regression")) %>%
    add_recipe(recipe(`Total Payment` ~ position + team,
                      data = finance_train) %>%
                 step_dummy(all_nominal()))
   
finance_model <- finance_rec %>%
     fit(data = finance_train) %>%
    predict(new_data = finance_test) %>% 
    bind_cols(finance_test %>% select(`Total Payment`)) 


 financial_graph <- finance_model %>%   
ggplot(aes(x = `Total Payment`, y = .pred)) + 
    geom_point(alpha = .2) + 
    geom_smooth(method = lm, formula = y ~ x, se = FALSE, col = "red") + 
    scale_x_log10() + 
    scale_y_log10() + 
    labs(y = "Predicted", x = "Total Payment in millions (GBP)") +
    labs(title = " Relationship between position and total payment")
 
 finance_model %>%
   metrics(truth = `Total Payment`, estimate = .pred)
 
 # The rmse values look similar to the total payment values in the finance_test
 # data frame which mean the error is small.
 
   
 

```

